//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.Core.Resources.ResourceVI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGeneralVI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGeneralVI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.Core.Resources.ResourceVI.ResourceGeneralVI", typeof(ResourceGeneralVI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exception_Msg_Common {
            get {
                return ResourceManager.GetString("Exception_Msg_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến máy chủ dữ liệu. Vui lòng thử lại hoặc liên hệ CSKH !.
        /// </summary>
        public static string Exception_Msg_DBConnection {
            get {
                return ResourceManager.GetString("Exception_Msg_DBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exception_Msg_InvalidDBData {
            get {
                return ResourceManager.GetString("Exception_Msg_InvalidDBData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Failed_Delete_Msg {
            get {
                return ResourceManager.GetString("Failed_Delete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin ID không hợp lệ. Không trùng khớp.
        /// </summary>
        public static string Validate_DevMsg_UnmatchedID {
            get {
                return ResourceManager.GetString("Validate_DevMsg_UnmatchedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;{1}&gt; đã tồn tại trong hệ thống, vui lòng kiểm tra lại !.
        /// </summary>
        public static string Validate_Msg_ExistedImportField {
            get {
                return ResourceManager.GetString("Validate_Msg_ExistedImportField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ CSKH !.
        /// </summary>
        public static string Validate_Msg_UnmatchedID {
            get {
                return ResourceManager.GetString("Validate_Msg_UnmatchedID", resourceCulture);
            }
        }
    }
}
