--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.636.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/3/2021 7:05:32 PM
-- Server version: 10.6.4
-- Client version: 4.1
--


-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `testdb`;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentID char(36) NOT NULL DEFAULT '' COMMENT 'ID đơn vị',
  DepartmentCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã phòng ban',
  DepartmentName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên đơn vị',
  Description varchar(255) DEFAULT '' COMMENT 'Thông tin mô tả',
  CreatedDate datetime DEFAULT NULL COMMENT 'Thời gian tạo',
  CreatedBy varchar(100) DEFAULT '' COMMENT 'Người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời gian chỉnh sửa cuối',
  ModifiedBy varchar(100) DEFAULT '' COMMENT 'Người chỉnh sửa cuối',
  PRIMARY KEY (DepartmentID)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Danh mục đơn vị / phòng ban';

DELIMITER $$

--
-- Create procedure `Proc_InsertDepartment`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_InsertDepartment (IN DepartmentCode varchar(255), IN DepartmentName varchar(255), IN Description varchar(255), IN CreatedDate varchar(255), IN CreatedBy varchar(255))
BEGIN
  INSERT INTO department (DepartmentID, DepartmentCode, DepartmentName, Description, CreatedDate, CreatedBy)
    VALUES (UUID(), DepartmentCode, DepartmentName, Description, NOW(), CreatedBy);
END
$$

--
-- Create procedure `Proc_GetDepartments`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetDepartments ()
BEGIN
  SELECT
    *
  FROM department d;
END
$$

DELIMITER ;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL DEFAULT '' COMMENT 'ID nhân viên',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã nhân viên',
  FullName varchar(100) NOT NULL DEFAULT '' COMMENT 'Họ và tên',
  DepartmentID char(36) DEFAULT '' COMMENT 'ID đơn vị / phòng ban',
  PositionName varchar(100) DEFAULT '' COMMENT 'Chức danh',
  DateOfBirth date DEFAULT NULL COMMENT 'Ngày sinh',
  Gender int(11) DEFAULT NULL COMMENT 'Giới tính',
  IdentityNumber varchar(25) DEFAULT NULL COMMENT 'Số CMND/CCCD',
  IdentityDate date DEFAULT NULL COMMENT 'Ngày cấp CMND/CCCD',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp CMND/CCCD',
  Address varchar(255) DEFAULT NULL COMMENT 'Đia chỉ',
  MobilePhoneNumber varchar(50) DEFAULT NULL COMMENT 'Số diện thoại di động',
  LandlinePhoneNumber varchar(50) DEFAULT NULL COMMENT 'Số điên thoại cố định',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  BankAccountNumber varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranch varchar(255) DEFAULT NULL COMMENT 'Chi nhánh ngân hàng',
  CreatedDate datetime DEFAULT NULL COMMENT 'Thời gian tạo bản ghi',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Thời gian cập nhật cuối',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Người cập nhật cuối',
  PRIMARY KEY (EmployeeID)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Danh mục nhân viên';

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_Employee_DepartmentID FOREIGN KEY (DepartmentID)
REFERENCES department (DepartmentID) ON DELETE NO ACTION ON UPDATE NO ACTION;

DELIMITER $$

--
-- Create procedure `Proc_InsertEmployee`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_InsertEmployee (IN EmployeeCode varchar(20), IN FullName varchar(100), IN DepartmentID char(36), IN PositionName varchar(100), IN DateOfBirth date, IN Gender int(11), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN Address varchar(255), IN MobilePhoneNumber varchar(50), IN LandlinePhoneNumber varchar(50), IN Email varchar(100), IN BankAccountNumber varchar(25), IN BankName varchar(255), IN BankBranch varchar(255), IN CreatedDate datetime, IN CreatedBy varchar(100), IN ModifiedDate datetime, IN ModifiedBy varchar(100))
BEGIN
  INSERT INTO employee (EmployeeID, EmployeeCode, FullName, DepartmentID, PositionName, DateOfBirth, Gender,
  IdentityNumber, IdentityDate, IdentityPlace, Address, MobilePhoneNumber, LandlinePhoneNumber,
  Email, BankAccountNumber, BankName, BankBranch, CreatedDate, CreatedBy)

    VALUES (UUID(), EmployeeCode, FullName, DepartmentID, PositionName, DateOfBirth, Gender, IdentityNumber, IdentityDate, IdentityPlace, Address, MobilePhoneNumber, LandlinePhoneNumber, Email, BankAccountNumber, BankName, BankBranch, NOW(), CreatedBy);
END
$$

--
-- Create procedure `Proc_CheckDuplicateField`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_CheckDuplicateField (IN FieldName varchar(255), IN FieldValue varchar(255))
COMMENT 'Lấy danh sách ID các bản ghi có thuộc tính trùng với giá trị tìm kiếm'
BEGIN

  SET @FieldName = (SELECT
      FieldName);
  SET @FieldValue = (SELECT
      FieldValue);

  SELECT
    COUNT(*)
  FROM employee e
  WHERE @FieldName LIKE CONCAT('%', @FieldValue, '%');

END
$$

DELIMITER ;

--
-- Create view `view_employee`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_employee
AS
SELECT
  `e`.`EmployeeID` AS `EmployeeID`,
  `e`.`EmployeeCode` AS `EmployeeCode`,
  `e`.`FullName` AS `FullName`,
  `e`.`PositionName` AS `PositionName`,
  `d`.`DepartmentName` AS `DepartmentName`,
  `e`.`DateOfBirth` AS `DateOfBirth`,
  `e`.`Gender` AS `Gender`,
  CASE WHEN `e`.`Gender` = 0 THEN 'Nam' WHEN `e`.`Gender` = 1 THEN 'Nữ' ELSE 'Khác' END AS `GenderName`,
  `e`.`IdentityNumber` AS `IdentityNumber`,
  `e`.`IdentityDate` AS `IdentityDate`,
  `e`.`IdentityPlace` AS `IdentityPlace`,
  `e`.`Address` AS `Address`,
  `e`.`MobilePhoneNumber` AS `MobilePhoneNumber`,
  `e`.`LandlinePhoneNumber` AS `LandlinePhoneNumber`,
  `e`.`Email` AS `Email`,
  `e`.`BankAccountNumber` AS `BankAccountNumber`,
  `e`.`BankName` AS `BankName`,
  `e`.`BankBranch` AS `BankBranch`,
  `d`.`DepartmentID` AS `DepartmentID`,
  `d`.`DepartmentCode` AS `DepartmentCode`
FROM (`employee` `e`
  LEFT JOIN `department` `d`
    ON (`e`.`DepartmentID` = `d`.`DepartmentID`));

DELIMITER $$

--
-- Create procedure `Proc_GetEmployees`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetEmployees ()
BEGIN
  SELECT
    *
  FROM view_employee ve;
END
$$

--
-- Create procedure `Proc_FilterEmployee`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_FilterEmployee (IN SearchKey varchar(100), IN PageNumber int, IN PageSize int, OUT TotalPage int, OUT TotalRecord int)
BEGIN
  DECLARE StartInd int DEFAULT 0;
  SET @SearchKey = (SELECT
      SearchKey);
  SET @PageNumber = (SELECT
      PageNumber);
  SET @PageSize = (SELECT
      PageSize);

  DROP TEMPORARY TABLE IF EXISTS TblFilter;

  IF @PageNumber * @PageSize > 0 THEN
    CREATE TEMPORARY TABLE TblFilter AS (SELECT
        ve.EmployeeID,
        ve.EmployeeCode,
        ve.FullName,
        ve.PositionName,
        ve.DepartmentName,
        ve.DateOfBirth,
        ve.Gender,
        ve.GenderName,
        ve.IdentityNumber,
        ve.IdentityDate,
        ve.IdentityPlace,
        ve.Address,
        ve.MobilePhoneNumber,
        ve.LandlinePhoneNumber,
        ve.Email,
        ve.BankAccountNumber,
        ve.BankName,
        ve.BankBranch,
        ve.DepartmentID,
        ve.DepartmentCode
      FROM view_employee ve
      WHERE (
      ve.EmployeeCode LIKE CONCAT('%', @SearchKey, '%')
      OR ve.FullName LIKE CONCAT('%', @SearchKey, '%')
      OR ve.MobilePhoneNumber LIKE CONCAT('%', @SearchKey, '%')
      OR ve.LandlinePhoneNumber LIKE CONCAT('%', @SearchKey, '%')
      OR @SearchKey IS NULL));
    SET TotalRecord = (SELECT
        COUNT(*)
      FROM TblFilter);
    SET TotalPage = CEIL((CAST(TotalRecord AS decimal) / CAST(PageSize AS decimal)));

    IF PageNumber > TotalPage THEN
      SET PageNumber = TotalPage;
    END IF;
    SET StartInd = ((PageNumber - 1) * PageSize);

    SELECT
      tf.EmployeeID,
      tf.EmployeeCode,
      tf.FullName,
      tf.PositionName,
      tf.DepartmentName,
      tf.DateOfBirth,
      tf.Gender,
      tf.IdentityNumber,
      tf.IdentityDate,
      tf.IdentityPlace,
      tf.Address,
      tf.MobilePhoneNumber,
      tf.LandlinePhoneNumber,
      tf.Email,
      tf.BankAccountNumber,
      tf.BankName,
      tf.BankBranch,
      tf.DepartmentID,
      tf.DepartmentCode
    FROM TblFilter tf
    ORDER BY tf.EmployeeCode DESC
    LIMIT StartInd, PageSize;
  END IF;
END
$$

DELIMITER ;

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'CV4', 'Phòng Công nghệ', 'Qui natus officiis. Vel temporibus et;', '2021-08-22 22:20:16', 'Minh Trịnh', '2021-08-27 08:52:48', 'Giang Trịnh'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'CV5', 'Phòng Đào tạo', 'Praesentium excepturi architecto. Sunt.', '2021-08-01 00:07:12', 'Hương Trần', '2021-08-27 00:00:04', 'Minh Lê'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'CV2', 'Phòng Nhân sự', 'Ullam sunt ut. Natus quia quas? Ut et!', '2021-08-05 19:30:55', 'Anh Tăng', '2021-08-27 12:23:23', 'Hương Trần'),
('469b3ece-744a-45d5-957d-e8c757976496', 'CV1', 'Phòng Tài chính', 'Molestiae autem sit. A nobis;', '2021-08-21 11:11:59', 'Thành Hoàng', '2021-08-27 12:06:43', 'Mai Hoàng'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'CV3', 'Phòng Kế toán', 'Facere accusantium ipsam. Enim.', '2021-08-06 14:44:29', 'Cường Trịnh', '2021-08-27 00:00:08', 'Mai Trần');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('12693b29-274c-35ce-d11d-086412a8ea97', 'NV-0039', 'Nguyễn Huy Thành ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '2003-12-17', 2, '', '2012-06-15', 'CA Lạng Sơn', 'Số 91 , Cầu Giấy, Cần Thơ', '0961 306 975', '(262) 414-2776', 'bpvzv8726@gmail.com', '160087449837', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 5', NULL, NULL, NULL, NULL),
('12e1b096-3542-127a-1077-d9ebc53aac3d', 'NV-0021', 'Hoàng Văn Minh ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1995-01-06', 2, '030007778138', '2012-11-29', 'CA Hòa Bình', 'Số 21 , Tây Sơn, Hà Giang', '0123 005 136', '(461) 201-6505', 'KristinaW_Williams@gmail.com', '051094705953', 'Ngân hàng Đông Nam Á', 'Chi nhánh 5', NULL, NULL, NULL, NULL),
('13ede5b6-19dd-563e-1980-de64d090a2c2', 'NV-0015', 'Nguyễn Thị Lan', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'HR', '1999-08-31', 2, '030099000123', '2017-07-12', 'CA Hà Giang', 'Số 36 , Xuân Thủy, Hà Nội', '0906 766 9444', '(201) 717-1444', 'WilberLaney444@misa.com', '051026858444', 'Techcombank', 'Chi nhánh 1', NULL, NULL, NULL, NULL),
('18baaac1-2b18-2317-b9d2-89b22d10517e', 'NV-0043', 'Trịnh Thị Loan ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '1991-10-20', 1, '055514326181', '2012-10-26', '', 'Số 78 , Tây Sơn, Phú Thọ', '0906 270 200', '(817) 337-1036', 'Fulton@gmail.com', '207038655347', 'Ngân hàng Tiên Phong', 'Chi nhánh 6', '2021-03-16 09:34:13', 'Hương', '2004-09-09 15:42:56', 'Mai Trần'),
('197fda97-5a35-781d-0e77-d9ebc53aac3d', 'NV-0005', 'Bùi Minh Mạnh ', '17120d02-6ab5-3e43-18cb-66948daf6128', NULL, NULL, NULL, '030098505917', NULL, NULL, NULL, NULL, '(219) 687-2284', NULL, '203049530372', NULL, 'Chi nhánh 5', NULL, 'Hân', '1973-08-26 18:40:36', NULL),
('1e5e96fa-5d7a-599d-27c2-579daad24557', 'NV-0008', 'Nguyễn Thị Hoa ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1992-08-13', 0, NULL, '2014-11-25', 'CA Cà Mau', '', '0336 122 618', '(730) 123-8017', '', '203082034699', 'Ngân hàng Á Châu', 'Chi nhánh 1', '2021-08-22 22:25:12', 'Cường', '1970-01-01 00:08:53', 'Linh Lê'),
('1f85f165-3ed3-370a-b7d2-89b22d10517e', 'NV-0028', 'Lê Ngọc Thái ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1997-01-16', 1, '035526694024', '2016-01-17', 'CA TP Hồ Chí Minh', 'Số 34 , Xuân Thủy, Thanh Hóa', '0336 896 764', '(509) 286-4139', 'RandellJ_Chism185@misa.com', '207051374481', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 5', '2021-01-01 00:14:28', 'Ngọc', '1985-01-05 19:25:10', 'Hường Nguyễn'),
('21a8748f-3464-740c-28c2-579daad24557', 'NV-0067', 'Lê Thái Trường ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Giám đốc', '2001-04-09', 2, '035513580396', '2015-12-29', NULL, 'Số 42 , Trần Hưng Đạo, Bắc Giang', '0336 999 453', '(127) 273-8561', 'Wolford931@gmail.com', '051022331907', 'Ngân hàng Đông Nam Á', 'Chi nhánh 5', '2021-07-06 11:39:39', 'Trường', '1970-01-01 00:08:32', NULL),
('22693b29-274c-35ce-d11d-086412a8ea97', 'NV-0089', 'Nguyễn Huy Thành ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '2003-12-17', 2, '', '2012-06-15', 'CA Lạng Sơn', 'Số 91 , Cầu Giấy, Cần Thơ', '0961 306 975', '(262) 414-2776', 'bpvzv8726@gmail.com', '160087449837', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 5', '2021-01-07 10:54:12', 'Thái', '2020-10-04 09:44:09', 'Minh Nguyễn'),
('22e1b096-3542-127a-1077-d9ebc53aac3d', 'NV-0071', 'Hoàng Văn Minh ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1995-01-06', 2, '030007778138', '2012-11-29', 'CA Hòa Bình', 'Số 21 , Tây Sơn, Hà Giang', '0123 005 136', '(461) 201-6505', 'KristinaW_Williams@gmail.com', '051094705953', 'Ngân hàng Đông Nam Á', 'Chi nhánh 5', '2021-03-24 17:46:13', 'Diễm', '1996-09-21 06:21:27', 'Ngọc Hoàng'),
('2356a2d8-7751-6f97-66f6-423b4e874d0f', 'NV-0026', 'Nguyễn Văn Hương ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Phó phòng', '1991-03-15', 0, '', '2015-02-27', 'CA Yên Bái', 'Số 22 , Âu Cơ, Yên Bái', '0906 660 982', '(140) 048-2558', 'Palma@gmail.com', '160091543498', 'Ngân hàng Quân đội', 'Chi nhánh 7', '2021-06-13 17:39:08', 'Cường', '1970-01-01 02:03:38', 'Hương Nguyễn'),
('23ede5b6-19dd-563e-1980-de64d090a2c2', 'NV-0065', 'Nguyễn Thị Lệ ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Phó phòng', '1992-08-31', 2, NULL, '2011-07-12', 'CA Hà Giang', 'Số 36 , Xuân Thủy, Hà Giang', '0906 766 933', '(201) 717-1066', 'WilberLaney@misa.com', '051026858048', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 0', NULL, NULL, NULL, NULL),
('28baaac1-2b18-2317-b9d2-89b22d10517e', 'NV-0093', 'Trịnh Thị Loan ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '1991-10-20', 1, '055514326181', '2012-10-26', '', 'Số 78 , Tây Sơn, Phú Thọ', '0906 270 200', '(817) 337-1036', 'Fulton@gmail.com', '207038655347', 'Ngân hàng Tiên Phong', 'Chi nhánh 6', '2021-03-16 09:34:13', 'Hương', '2004-09-09 15:42:56', 'Mai Trần'),
('28cd1599-63bf-785f-4f80-7ed9d1ea06ea', 'NV-0006', 'Tăng Huy Hùng ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1992-10-28', 0, '030006622845', '2015-12-04', '', 'Số 92 , Quang Trung, Bình Dương', '0906 930 292', '(784) 105-7292', 'JeremyHaywood255@gmail.com', '203009528476', 'Ngân hàng Á Châu', 'Chi nhánh 5', '2021-02-05 19:07:02', 'Loan', '2009-03-15 10:28:13', 'Hiếu Trần'),
('297fda97-5a35-781d-0e77-d9ebc53aac3d', 'NV-0055', 'Bùi Minh Mạnh ', '17120d02-6ab5-3e43-18cb-66948daf6128', NULL, NULL, NULL, '030098505917', NULL, NULL, NULL, NULL, '(219) 687-2284', NULL, '203049530372', NULL, 'Chi nhánh 5', NULL, 'Hân', '1973-08-26 18:40:36', NULL),
('2afb2146-430d-394b-3d35-0028ed526dd0', 'NV-0047', 'Nguyễn Đức Huy ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1994-03-28', 1, '035579097387', '2013-07-12', '', 'Số 26 , Xuân Thủy, Nam Định', '0123 424 954', '(120) 921-7713', 'Siobhan.Leger@gmail.com', '160094967897', 'Ngân hàng Tiên Phong', 'Chi nhánh 2', '2021-01-01 00:01:02', 'Hương', '2014-07-27 00:14:58', 'Ngọc Tăng'),
('2e5e96fa-5d7a-599d-27c2-579daad24557', 'NV-0058', 'Nguyễn Thị Hoa ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1992-08-13', 0, NULL, '2014-11-25', 'CA Cà Mau', '', '0336 122 618', '(730) 123-8017', '', '203082034699', 'Ngân hàng Á Châu', 'Chi nhánh 1', '2021-08-22 22:25:12', 'Cường', '1970-01-01 00:08:53', 'Linh Lê'),
('2f43fc9d-1f7a-25fc-5280-7ed9d1ea06ea', 'NV-0042', 'Nguyễn Hương Mai ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1991-01-06', 2, '035564831499', '2011-03-17', 'CA Bắc Ninh', 'Số 33 , Nguyễn Trãi, Bình Dương', '0906 507 690', '(642) 511-0916', 'Ewing@gmail.com', '160098214857', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 9', '2021-03-30 17:00:02', 'Minh', '1970-01-01 02:04:26', NULL),
('2f85f165-3ed3-370a-b7d2-89b22d10517e', 'NV-0078', 'Lê Ngọc Thái ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1997-01-16', 1, '035526694024', '2016-01-17', 'CA TP Hồ Chí Minh', 'Số 34 , Xuân Thủy, Thanh Hóa', '0336 896 764', '(509) 286-4139', 'RandellJ_Chism185@misa.com', '207051374481', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 5', '2021-01-01 00:14:28', 'Ngọc', '1985-01-05 19:25:10', 'Hường Nguyễn'),
('3304dddb-1b72-607f-25c2-579daad24557', 'NV-0000', 'Nguyễn Ngọc Hùng ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Giám đốc', '1991-01-20', 1, '030078382727', '2011-12-23', 'CA Nam Định', 'Số 41 , Trần Hưng Đạo, Nghệ An', '0961 339 091', '(141) 952-2282', 'Conrad_Frizzell61@gmail.com', '207080379092', 'Ngân hàng Tiên Phong', 'Chi nhánh 9', '2021-01-20 21:24:13', 'Bằng', '1993-12-26 02:04:39', 'Mạnh Trịnh'),
('3356a2d8-7751-6f97-66f6-423b4e874d0f', 'NV-0076', 'Nguyễn Văn Hương ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Phó phòng', '1991-03-15', 0, '', '2015-02-27', 'CA Yên Bái', 'Số 22 , Âu Cơ, Yên Bái', '0906 660 982', '(140) 048-2558', 'Palma@gmail.com', '160091543498', 'Ngân hàng Quân đội', 'Chi nhánh 7', '2021-06-13 17:39:08', 'Cường', '1970-01-01 02:03:38', 'Hương Nguyễn'),
('35c3a053-254d-33f3-1b80-de64d090a2c2', 'NV-0035', 'Nguyễn Đức Thái ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1997-02-16', 0, '055549341296', '2018-01-13', NULL, 'Số 11 , Xuân Thủy, Thái Bình', '0123 471 811', '(865) 330-2737', 'Adah_N_Wofford@gmail.com', '207081694933', 'Ngân hàng Á Châu', 'Chi nhánh 7', '2021-04-10 04:36:29', 'Tuấn', '1970-01-01 00:09:09', NULL),
('36ac2df8-2b1e-368f-cc1d-086412a8ea97', 'NV-0009', 'Nguyễn Mai Hân ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '2000-06-17', 1, '', '2013-10-04', 'CA Thái Bình', 'Số 84 , Cầu Giấy, Hà Nam', '0123 911 733', '(434) 214-4385', 'Edward.B_Craddock933@misa.com', '160025274765', 'Ngân hàng Tiên Phong', 'Chi nhánh 3', '2021-08-02 02:40:57', 'Mạnh', '1970-01-01 00:04:54', 'Hiếu Bùi'),
('3738ce93-1661-5628-2cc2-579daad24557', 'NV-0049', 'Hoàng Hương Hương ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '2003-10-25', 0, '035561845221', '2017-08-11', NULL, 'Số 65 , Quang Trung, Nghệ An', '0906 033 366', '(498) 950-5924', 'Wise938@gmail.com', '203004810196', 'Ngân hàng Quân đội', 'Chi nhánh 5', '2021-06-30 21:47:53', 'Hân', '1970-01-01 00:00:44', NULL),
('38cd1599-63bf-785f-4f80-7ed9d1ea06ea', 'NV-0056', 'Tăng Huy Hùng ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1992-10-28', 0, '030006622845', '2015-12-04', '', 'Số 92 , Quang Trung, Bình Dương', '0906 930 292', '(784) 105-7292', 'JeremyHaywood255@gmail.com', '203009528476', 'Ngân hàng Á Châu', 'Chi nhánh 5', '2021-02-05 19:07:02', 'Loan', '2009-03-15 10:28:13', 'Hiếu Trần'),
('3afb2146-430d-394b-3d35-0028ed526dd0', 'NV-0097', 'Nguyễn Đức Huy ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1994-03-28', 1, '035579097387', '2013-07-12', '', 'Số 26 , Xuân Thủy, Nam Định', '0123 424 954', '(120) 921-7713', 'Siobhan.Leger@gmail.com', '160094967897', 'Ngân hàng Tiên Phong', 'Chi nhánh 2', '2021-01-01 00:01:02', 'Hương', '2014-07-27 00:14:58', 'Ngọc Tăng'),
('3e51a46c-4153-229c-7f41-c1ec321fe728', 'NV-0033', 'Nguyễn Văn Tuấn ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Phó phòng', '1991-03-12', 2, NULL, '2010-03-12', 'CA Cần Thơ', 'Số 72 , Tây Sơn, Hà Giang', '0123 941 494', NULL, 'Haynes@misa.com', '160073142874', 'Ngân hàng Kỹ Thương Việt Nam', NULL, '2021-02-03 10:20:09', NULL, NULL, 'Hiếu Tăng'),
('3e7dd0ec-7ee5-392a-1277-d9ebc53aac3d', 'NV-0040', 'Bùi Văn Tuấn ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '2003-08-08', 0, '035555877790', '2016-12-31', 'CA Yên Bái', 'Số 41 , Tây Sơn, Hà Giang', '0961 124 695', '(720) 150-6341', 'HoseaCBlake@misa.com', '051078881985', 'Ngân hàng Á Châu', 'Chi nhánh 1', '2021-01-01 00:14:57', 'Lệ', '2010-07-28 13:38:51', 'Ngọc Hoàng'),
('3f43fc9d-1f7a-25fc-5280-7ed9d1ea06ea', 'NV-0092', 'Nguyễn Hương Mai ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1991-01-06', 2, '035564831499', '2011-03-17', 'CA Bắc Ninh', 'Số 33 , Nguyễn Trãi, Bình Dương', '0906 507 690', '(642) 511-0916', 'Ewing@gmail.com', '160098214857', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 9', '2021-03-30 17:00:02', 'Minh', '1970-01-01 02:04:26', NULL),
('3fed64ec-2f94-798f-0335-60b3ebf808a9', 'NV-0045', 'Trần Thị Hoa ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '2000-08-06', 2, '055504689042', '2018-02-27', 'CA Vĩnh Phúc', '', '0123 038 334', '(985) 271-0853', '', '207019296165', 'Ngân hàng Đông Nam Á', 'Chi nhánh 0', '2021-08-24 15:59:17', 'Trường', '2003-10-17 13:55:09', 'Linh Bùi'),
('407db4d1-222b-287d-0135-60b3ebf808a9', 'NV-0020', 'Trần Mai Hương ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1995-09-04', 0, '035573398780', '2013-02-11', '', 'Số 36 , Trần Hưng Đạo, Thanh Hóa', '0906 666 369', '(521) 366-3991', 'Scruggs@gmail.com', '207027345819', 'Ngân hàng Quân đội', 'Chi nhánh 3', '2021-01-01 01:00:32', 'Ngọc', '2002-03-20 13:59:02', 'Lệ Nguyễn'),
('409dcd1a-426a-23f7-3a35-0028ed526dd0', 'NV-0011', 'Nguyễn Thị Giang ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '2000-01-07', 2, '055522270718', '2014-05-06', 'CA Hải Dương', 'Số 66 , Quang Trung, Hải Dương', '0123 293 143', '(303) 661-0123', 'ndjketfq_rjzwqjx@gmail.com', '051090960285', 'Ngân hàng Đông Nam Á', 'Chi nhánh 0', '2021-07-21 13:01:03', 'Huy', '2003-01-18 17:33:07', 'Mạnh Trần'),
('42b9446a-790b-3892-2ac2-579daad24557', 'NV-0032', 'Nguyễn Đức Thái ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Giám đốc', '1999-11-09', 1, '055522928523', '2013-07-26', '', '', '0123 909 094', '(110) 812-6926', '', '203085088411', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 2', '2021-05-30 16:53:23', 'Hương', '1978-09-21 23:24:04', 'Mạnh Lê'),
('4304dddb-1b72-607f-25c2-579daad24557', 'NV-0050', 'Nguyễn Ngọc Hùng ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Giám đốc', '1991-01-20', 1, '030078382727', '2011-12-23', 'CA Nam Định', 'Số 41 , Trần Hưng Đạo, Nghệ An', '0961 339 091', '(141) 952-2282', 'Conrad_Frizzell61@gmail.com', '207080379092', 'Ngân hàng Tiên Phong', 'Chi nhánh 9', '2021-01-20 21:24:13', 'Bằng', '1993-12-26 02:04:39', 'Mạnh Trịnh'),
('45c3a053-254d-33f3-1b80-de64d090a2c2', 'NV-0085', 'Nguyễn Đức Thái ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1997-02-16', 0, '055549341296', '2018-01-13', NULL, 'Số 11 , Xuân Thủy, Thái Bình', '0123 471 811', '(865) 330-2737', 'Adah_N_Wofford@gmail.com', '207081694933', 'Ngân hàng Á Châu', 'Chi nhánh 7', '2021-04-10 04:36:29', 'Tuấn', '1970-01-01 00:09:09', NULL),
('46ac2df8-2b1e-368f-cc1d-086412a8ea97', 'NV-0059', 'Nguyễn Mai Hân ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '2000-06-17', 1, '', '2013-10-04', 'CA Thái Bình', 'Số 84 , Cầu Giấy, Hà Nam', '0123 911 733', '(434) 214-4385', 'Edward.B_Craddock933@misa.com', '160025274765', 'Ngân hàng Tiên Phong', 'Chi nhánh 3', '2021-08-02 02:40:57', 'Mạnh', '1970-01-01 00:04:54', 'Hiếu Bùi'),
('4738ce93-1661-5628-2cc2-579daad24557', 'NV-0099', 'Hoàng Hương Lan', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '2003-10-25', 1, '035561845221', '2017-08-11', NULL, 'Số 65 , Quang Trung, Nghệ An', '0906 033 366', '(498) 950-5924', 'Wise938@gmail.com', '203004810196', 'Ngân hàng Quân đội', 'Chi nhánh 5', NULL, NULL, NULL, NULL),
('481183cb-5a6c-795b-68f6-423b4e874d0f', 'NV-0044', 'Trịnh Thị Lệ ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, '(272) 641-3476', NULL, '203066942993', NULL, 'Chi nhánh 2', NULL, 'Hùng', '2015-05-21 06:19:16', NULL),
('4989ff24-23e7-7b82-b6d2-89b22d10517e', 'NV-0022', 'Hoàng Văn Mạnh ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1992-11-08', 0, NULL, '2011-11-09', 'CA Bình Dương', 'Số 45 , Trần Hưng Đạo, Hải Phòng', '0906 619 451', '(321) 710-8523', 'Henry8@gmail.com', '051030489011', 'Ngân hàng Á Châu', 'Chi nhánh 9', '2021-07-11 12:52:51', 'Giang', '2005-05-29 06:33:55', 'Linh Bùi'),
('4db9a514-6d87-2ec1-3b35-0028ed526dd0', 'NV-0031', 'Nguyễn Minh Thành ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '1993-08-04', 2, '035548260430', '2012-08-04', 'CA Hưng Yên', '', '0961 239 369', '(356) 036-5906', '', '051051281570', 'Ngân hàng Đông Nam Á', 'Chi nhánh 2', '2021-05-15 07:07:22', 'Hân', '1983-09-29 23:16:23', 'Cường Hoàng'),
('4e51a46c-4153-229c-7f41-c1ec321fe728', 'NV-0083', 'Nguyễn Văn Tuấn ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Phó phòng', '1991-03-12', 2, NULL, '2010-03-12', 'CA Cần Thơ', 'Số 72 , Tây Sơn, Hà Giang', '0123 941 494', NULL, 'Haynes@misa.com', '160073142874', 'Ngân hàng Kỹ Thương Việt Nam', NULL, '2021-02-03 10:20:09', NULL, NULL, 'Hiếu Tăng'),
('4e7dd0ec-7ee5-392a-1277-d9ebc53aac3d', 'NV-0090', 'Bùi Văn Tuấn ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '2003-08-08', 0, '035555877790', '2016-12-31', 'CA Yên Bái', 'Số 41 , Tây Sơn, Hà Giang', '0961 124 695', '(720) 150-6341', 'HoseaCBlake@misa.com', '051078881985', 'Ngân hàng Á Châu', 'Chi nhánh 1', '2021-01-01 00:14:57', 'Lệ', '2010-07-28 13:38:51', 'Ngọc Hoàng'),
('4fed64ec-2f94-798f-0335-60b3ebf808a9', 'NV-0095', 'Trần Thị Hoa ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '2000-08-06', 2, '055504689042', '2018-02-27', 'CA Vĩnh Phúc', '', '0123 038 334', '(985) 271-0853', '', '207019296165', 'Ngân hàng Đông Nam Á', 'Chi nhánh 0', '2021-08-24 15:59:17', 'Trường', '2003-10-17 13:55:09', 'Linh Bùi'),
('506acf1e-5331-67a9-0d77-d9ebc53aac3d', 'NV-0002', 'Nguyễn Thị Hường ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1993-01-29', 1, '055594156031', '2016-07-14', 'CA Hà Giang', NULL, '0336 432 033', '(375) 580-5172', NULL, '207007332383', 'Ngân hàng Tiên Phong', 'Chi nhánh 1', '2021-04-13 11:43:04', 'Loan', '2020-02-12 15:32:58', 'Ly Trần'),
('507db4d1-222b-287d-0135-60b3ebf808a9', 'NV-0070', 'Trần Mai Hương ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1995-09-04', 0, '035573398780', '2013-02-11', '', 'Số 36 , Trần Hưng Đạo, Thanh Hóa', '0906 666 369', '(521) 366-3991', 'Scruggs@gmail.com', '207027345819', 'Ngân hàng Quân đội', 'Chi nhánh 3', '2021-01-01 01:00:32', 'Ngọc', '2002-03-20 13:59:02', 'Lệ Nguyễn'),
('509dcd1a-426a-23f7-3a35-0028ed526dd0', 'NV-0061', 'Nguyễn Thị Giang ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '2000-01-07', 2, '055522270718', '2014-05-06', 'CA Hải Dương', 'Số 66 , Quang Trung, Hải Dương', '0123 293 143', '(303) 661-0123', 'ndjketfq_rjzwqjx@gmail.com', '051090960285', 'Ngân hàng Đông Nam Á', 'Chi nhánh 0', '2021-07-21 13:01:03', 'Huy', '2003-01-18 17:33:07', 'Mạnh Trần'),
('524751f2-1577-523d-ce1d-086412a8ea97', 'NV-0019', 'Nguyễn Đức Mạnh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '2001-11-03', 0, '055542396008', '2016-06-01', '', 'Số 84 , Trần Hưng Đạo, Phú Thọ', '0906 844 604', '(643) 828-1801', 'Teresia_Avalos@misa.com', '160017835002', 'Ngân hàng Á Châu', 'Chi nhánh 8', '2021-02-18 01:43:17', 'Mạnh', '2007-07-17 14:30:12', 'Hương Nguyễn'),
('5254e49d-4368-3162-29c2-579daad24557', 'NV-0027', 'Nguyễn Thái Bằng ', '469b3ece-744a-45d5-957d-e8c757976496', 'Giám đốc', '1998-06-20', 1, '055566466267', '2013-06-20', NULL, 'Số 43 , Trần Hưng Đạo, Hà Giang', '0961 018 992', '(908) 576-4434', 'Abbie.Sample@misa.com', '160008038273', 'Ngân hàng Tiên Phong', 'Chi nhánh 7', '2021-08-23 20:15:18', 'Hương', '1986-08-26 04:52:42', NULL),
('52b9446a-790b-3892-2ac2-579daad24557', 'NV-0082', 'Nguyễn Đức Thái ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Giám đốc', '1999-11-09', 1, '055522928523', '2013-07-26', '', '', '0123 909 094', '(110) 812-6926', '', '203085088411', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 2', '2021-05-30 16:53:23', 'Hương', '1978-09-21 23:24:04', 'Mạnh Lê'),
('56aaf263-3355-23ea-b8d2-89b22d10517e', 'NV-0037', 'Trần Đức Huy ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '1995-08-03', 0, '055566025564', '2012-03-29', 'CA Lào Cai', 'Số 92 , Cầu Giấy, Hòa Bình', '0123 512 201', '(660) 760-7750', 'GusBurnett741@misa.com', '203097208650', 'Ngân hàng Á Châu', 'Chi nhánh 3', '2021-06-09 08:00:15', 'Lệ', '1970-01-01 02:37:34', 'Hương Trần'),
('56dce332-76f0-6b9b-5080-7ed9d1ea06ea', 'NV-0016', 'Nguyễn Minh Mạnh ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '2001-03-21', 2, '', '2018-02-22', NULL, '', '0336 799 657', '(363) 302-0571', '', '160050226202', 'Ngân hàng Đông Nam Á', 'Chi nhánh 5', '2021-07-04 20:47:42', 'Mạnh', '1984-06-02 10:57:38', NULL),
('57cdf8c4-47e3-5560-7e41-c1ec321fe728', 'NV-0001', 'Nguyễn Minh Anh ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', NULL, NULL, NULL, '055596851683', NULL, 'CA Cần Thơ', NULL, NULL, '(423) 916-0439', NULL, '207004600189', NULL, 'Chi nhánh 2', NULL, 'Tuấn', '2008-11-11 03:09:35', 'Anh Lê'),
('595e7d51-318c-39e8-1377-d9ebc53aac3d', 'NV-0048', 'Nguyễn Thị Diễm ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1991-01-17', 1, '035526834074', '2017-04-30', NULL, 'Số 31 , Hồ Tùng Mậu, Nghệ An', '0961 613 194', '(221) 181-9134', 'LissaKrebs@gmail.com', '160041954358', 'Ngân hàng Tiên Phong', 'Chi nhánh 6', '2021-01-04 19:17:57', 'Mai', '2012-04-06 12:29:03', NULL),
('5989ff24-23e7-7b82-b6d2-89b22d10517e', 'NV-0072', 'Hoàng Văn Mạnh ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1992-11-08', 0, NULL, '2011-11-09', 'CA Bình Dương', 'Số 45 , Trần Hưng Đạo, Hải Phòng', '0906 619 451', '(321) 710-8523', 'Henry8@gmail.com', '051030489011', 'Ngân hàng Á Châu', 'Chi nhánh 9', '2021-07-11 12:52:51', 'Giang', '2005-05-29 06:33:55', 'Linh Bùi'),
('5a841b92-791c-78df-5180-7ed9d1ea06ea', 'NV-0034', 'Trịnh Thị Hường ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Giám đốc', '2002-12-08', 0, '030028628525', '2014-01-09', 'CA Bắc Ninh', 'Số 12 , Cầu Giấy, Bắc Ninh', '0906 476 344', '(529) 911-9415', 'Guest76@gmail.com', '203006452696', 'Ngân hàng Á Châu', 'Chi nhánh 6', '2021-01-01 00:00:12', 'Huy', '2005-05-08 21:24:17', 'Hương Trịnh'),
('5c7f0ec4-77f2-3794-cf1d-086412a8ea97', 'NV-0023', 'Nguyễn Thị Linh ', '469b3ece-744a-45d5-957d-e8c757976496', 'Phó phòng', '1995-04-08', 1, '035596191056', '2011-02-10', 'CA Hòa Bình', 'Số 93 , Âu Cơ, Nam Định', '0123 707 521', '(522) 128-9842', 'wnyfeyzw_nniur@gmail.com', '207036419863', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 1', '2021-02-24 05:27:32', 'Ngọc', '2009-09-30 06:37:50', 'Trường Trịnh'),
('5db9a514-6d87-2ec1-3b35-0028ed526dd0', 'NV-0081', 'Nguyễn Minh Thành ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '1993-08-04', 2, '035548260430', '2012-08-04', 'CA Hưng Yên', '', '0961 239 369', '(356) 036-5906', '', '051051281570', 'Ngân hàng Đông Nam Á', 'Chi nhánh 2', '2021-05-15 07:07:22', 'Hân', '1983-09-29 23:16:23', 'Cường Hoàng'),
('5de704c2-573f-1a71-1a80-de64d090a2c2', 'NV-0024', 'Trần Hương Giang ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', NULL, NULL, NULL, '030068023210', NULL, NULL, NULL, NULL, '(469) 512-8980', NULL, '051041798422', NULL, 'Chi nhánh 9', NULL, 'Ngọc', '2011-01-12 02:05:42', NULL),
('5f03d745-7702-1c85-2bc2-579daad24557', 'NV-0046', 'Trịnh Ngọc Mạnh ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '1991-01-02', 1, '055526370992', '2010-03-03', 'CA Thanh Hóa', 'Số 75 , Quang Trung, Bắc Giang', '0123 648 415', '(822) 047-6617', 'Buss@gmail.com', '051091493850', 'Ngân hàng Tiên Phong', 'Chi nhánh 5', '2021-02-08 15:27:18', 'Ly', '2019-08-16 10:34:50', 'Mai Nguyễn'),
('5fab4ff7-1b8e-64d0-1880-de64d090a2c2', 'NV-0007', 'Nguyễn Hương Ngọc ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Trưởng phòng', '1993-04-15', 1, '055541051944', '2012-04-15', 'CA Nghệ An', 'Số 62 , Trần Hưng Đạo, Thanh Hóa', '0961 458 866', '(465) 098-1888', 'KearneyG616@gmail.com', '160038770683', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 1', '2021-01-17 15:05:59', 'Diễm', '2012-07-16 00:03:10', NULL),
('606acf1e-5331-67a9-0d77-d9ebc53aac3d', 'NV-0052', 'Nguyễn Thị Hường ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '1993-01-29', 1, '055594156031', '2016-07-14', 'CA Hà Giang', NULL, '0336 432 033', '(375) 580-5172', NULL, '207007332383', 'Ngân hàng Tiên Phong', 'Chi nhánh 1', '2021-04-13 11:43:04', 'Loan', '2020-02-12 15:32:58', 'Ly Trần'),
('624751f2-1577-523d-ce1d-086412a8ea97', 'NV-0069', 'Nguyễn Đức Mạnh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '2001-11-03', 0, '055542396008', '2016-06-01', '', 'Số 84 , Trần Hưng Đạo, Phú Thọ', '0906 844 604', '(643) 828-1801', 'Teresia_Avalos@misa.com', '160017835002', 'Ngân hàng Á Châu', 'Chi nhánh 8', '2021-02-18 01:43:17', 'Mạnh', '2007-07-17 14:30:12', 'Hương Nguyễn'),
('6254e49d-4368-3162-29c2-579daad24557', 'NV-0077', 'Nguyễn Thái Bằng ', '469b3ece-744a-45d5-957d-e8c757976496', 'Giám đốc', '1998-06-20', 1, '055566466267', '2013-06-20', NULL, 'Số 43 , Trần Hưng Đạo, Hà Giang', '0961 018 992', '(908) 576-4434', 'Abbie.Sample@misa.com', '160008038273', 'Ngân hàng Tiên Phong', 'Chi nhánh 7', '2021-08-23 20:15:18', 'Hương', '1986-08-26 04:52:42', NULL),
('62563348-7bd5-6519-3c35-0028ed526dd0', 'NV-0036', 'Nguyễn Thị Linh ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Giám đốc', '1999-04-10', 2, '055548091982', '2010-09-01', 'CA Yên Bái', NULL, '0906 834 148', '(539) 917-0954', NULL, '160011322239', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 7', '2021-03-30 00:37:59', 'Hường', '1970-01-01 01:37:34', 'Hoa Nguyễn'),
('62af2231-78a7-7caa-cd1d-086412a8ea97', 'NV-0014', 'Trịnh Huy Thành ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Trưởng phòng', '1994-01-28', 1, '035552219492', '2013-03-11', 'CA Thanh Hóa', 'Số 87 , Âu Cơ, Khánh Hòa', '0123 619 265', '(173) 454-3055', 'Antonina_H.Criswell@misa.com', '203068938773', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 5', '2021-07-16 23:42:18', 'Hường', '1970-01-01 00:00:06', 'Thái Trịnh'),
('6485b64f-7835-65a4-8041-c1ec321fe728', 'NV-0041', 'Hoàng Ngọc Hiếu ', '469b3ece-744a-45d5-957d-e8c757976496', 'Giám đốc', '1991-06-15', 0, '030026574909', '2016-07-26', NULL, 'Số 87 , Quang Trung, TP Hồ Chí Minh', '0336 964 684', '(357) 663-5567', 'Hudgens@misa.com', '051065784092', 'Ngân hàng Á Châu', 'Chi nhánh 7', '2021-01-11 19:42:19', 'Loan', '2020-07-31 21:06:39', NULL),
('66aaf263-3355-23ea-b8d2-89b22d10517e', 'NV-0087', 'Trần Đức Huy ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '1995-08-03', 0, '055566025564', '2012-03-29', 'CA Lào Cai', 'Số 92 , Cầu Giấy, Hòa Bình', '0123 512 201', '(660) 760-7750', 'GusBurnett741@misa.com', '203097208650', 'Ngân hàng Á Châu', 'Chi nhánh 3', '2021-06-09 08:00:15', 'Lệ', '1970-01-01 02:37:34', 'Hương Trần'),
('66dce332-76f0-6b9b-5080-7ed9d1ea06ea', 'NV-0066', 'Nguyễn Minh Mạnh ', '142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nhân viên', '2001-03-21', 2, '', '2018-02-22', NULL, '', '0336 799 657', '(363) 302-0571', '', '160050226202', 'Ngân hàng Đông Nam Á', 'Chi nhánh 5', '2021-07-04 20:47:42', 'Mạnh', '1984-06-02 10:57:38', NULL),
('677132b4-2a33-68d1-26c2-579daad24557', 'NV-0004', 'Nguyễn Đức Tuấn ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '2003-12-29', 0, '035567754881', '2018-02-21', 'CA Yên Bái', '', '0906 618 560', '(465) 824-3043', '', '160078416506', 'Ngân hàng Quân đội', 'Chi nhánh 9', '2021-07-12 22:07:30', 'Trường', '1975-02-24 02:44:03', 'Hương Nguyễn'),
('67cdf8c4-47e3-5560-7e41-c1ec321fe728', 'NV-0051', 'Nguyễn Minh Anh ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', NULL, NULL, NULL, '055596851683', NULL, 'CA Cần Thơ', NULL, NULL, '(423) 916-0439', NULL, '207004600189', NULL, 'Chi nhánh 2', NULL, 'Tuấn', '2008-11-11 03:09:35', 'Anh Lê'),
('695e7d51-318c-39e8-1377-d9ebc53aac3d', 'NV-0098', 'Nguyễn Thị Diễm ', '469b3ece-744a-45d5-957d-e8c757976496', 'Nhân viên', '1991-01-17', 1, '035526834074', '2017-04-30', NULL, 'Số 31 , Hồ Tùng Mậu, Nghệ An', '0961 613 194', '(221) 181-9134', 'LissaKrebs@gmail.com', '160041954358', 'Ngân hàng Tiên Phong', 'Chi nhánh 6', '2021-01-04 19:17:57', 'Mai', '2012-04-06 12:29:03', NULL),
('6a763a51-4322-5c5a-b5d2-89b22d10517e', 'NV-0018', 'Tăng Ngọc Linh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Trưởng phòng', '2001-05-26', 2, '', '2010-06-02', 'CA Thanh Hóa', 'Số 27 , Cầu Giấy, Lào Cai', '0336 849 980', '(865) 520-4431', 'Asher@misa.com', '203045695969', 'Ngân hàng Đông Nam Á', 'Chi nhánh 8', '2021-06-05 18:20:28', 'Ly', '1970-01-01 02:05:18', 'Minh Bùi'),
('6a841b92-791c-78df-5180-7ed9d1ea06ea', 'NV-0084', 'Trịnh Thị Hường ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Giám đốc', '2002-12-08', 0, '030028628525', '2014-01-09', 'CA Bắc Ninh', 'Số 12 , Cầu Giấy, Bắc Ninh', '0906 476 344', '(529) 911-9415', 'Guest76@gmail.com', '203006452696', 'Ngân hàng Á Châu', 'Chi nhánh 6', '2021-01-01 00:00:12', 'Huy', '2005-05-08 21:24:17', 'Hương Trịnh'),
('6b550b8f-7ff9-51bc-0f77-d9ebc53aac3d', 'NV-0012', 'Bùi Thị Diễm ', '142cb08f-7c31-21fa-8e90-67245e8b283e', NULL, NULL, NULL, '035572786876', NULL, 'CA Hà Nam', NULL, NULL, '(875) 588-3115', NULL, '160065134493', NULL, 'Chi nhánh 4', NULL, 'Linh', '1979-12-01 15:08:55', 'Thái Hoàng'),
('6c5b9fe7-14c9-3bb5-b4d2-89b22d10517e', 'NV-0013', 'Hoàng Văn Tuấn ', '469b3ece-744a-45d5-957d-e8c757976496', 'Phó phòng', '2001-09-01', 2, NULL, '2012-04-28', 'CA Hòa Bình', 'Số 92 , Nguyễn Trãi, Thanh Hóa', '0123 791 603', NULL, 'WaltonGolden1@misa.com', '160003587696', 'Ngân hàng Kỹ Thương Việt Nam', NULL, '2021-01-01 00:00:07', NULL, NULL, 'Loan Nguyễn'),
('6c7f0ec4-77f2-3794-cf1d-086412a8ea97', 'NV-0073', 'Nguyễn Thị Linh ', '469b3ece-744a-45d5-957d-e8c757976496', 'Phó phòng', '1995-04-08', 1, '035596191056', '2011-02-10', 'CA Hòa Bình', 'Số 93 , Âu Cơ, Nam Định', '0123 707 521', '(522) 128-9842', 'wnyfeyzw_nniur@gmail.com', '207036419863', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 1', '2021-02-24 05:27:32', 'Ngọc', '2009-09-30 06:37:50', 'Trường Trịnh'),
('6c80a684-1cb5-41af-ff34-60b3ebf808a9', 'NV-0003', 'Tăng Ngọc Bằng ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Giám đốc', '1992-01-24', 0, '030072193572', '2012-11-07', 'CA Hòa Bình', '', '0906 267 622', '(450) 290-3993', '', '207006976149', 'Ngân hàng Á Châu', 'Chi nhánh 7', '2021-01-01 01:19:23', 'Hoa', '1975-02-13 04:47:19', 'Thái Tăng'),
('6d71399b-0bdd-11ec-b02c-54e1ad9d060b', 'aaaa', 'aaaa', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2021-09-02 18:03:39', NULL, NULL, NULL),
('6de704c2-573f-1a71-1a80-de64d090a2c2', 'NV-0074', 'Trần Hương Giang ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', NULL, NULL, NULL, '030068023210', NULL, NULL, NULL, NULL, '(469) 512-8980', NULL, '051041798422', NULL, 'Chi nhánh 9', NULL, 'Ngọc', '2011-01-12 02:05:42', NULL),
('6f03d745-7702-1c85-2bc2-579daad24557', 'NV-0096', 'Trịnh Ngọc Mạnh ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '1991-01-02', 1, '055526370992', '2010-03-03', 'CA Thanh Hóa', 'Số 75 , Quang Trung, Bắc Giang', '0123 648 415', '(822) 047-6617', 'Buss@gmail.com', '051091493850', 'Ngân hàng Tiên Phong', 'Chi nhánh 5', '2021-02-08 15:27:18', 'Ly', '2019-08-16 10:34:50', 'Mai Nguyễn'),
('6f51ea57-13b2-139f-1177-d9ebc53aac3d', 'NV-0030', 'Nguyễn Thái Hùng ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '1996-06-29', 1, '030013314688', '2014-02-16', 'CA Hà Giang', NULL, '0961 361 849', '(198) 058-4532', NULL, '051051633266', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 3', '2021-03-27 03:57:07', 'Hường', '2002-12-28 21:18:40', 'Huy Trịnh'),
('6fab4ff7-1b8e-64d0-1880-de64d090a2c2', 'NV-0057', 'Nguyễn Hương Ngọc ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Trưởng phòng', '1993-04-15', 1, '055541051944', '2012-04-15', 'CA Nghệ An', 'Số 62 , Trần Hưng Đạo, Thanh Hóa', '0961 458 866', '(465) 098-1888', 'KearneyG616@gmail.com', '160038770683', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 1', '2021-01-17 15:05:59', 'Diễm', '2012-07-16 00:03:10', NULL),
('72563348-7bd5-6519-3c35-0028ed526dd0', 'NV-0086', 'Nguyễn Thị Linh ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Giám đốc', '1999-04-10', 2, '055548091982', '2010-09-01', 'CA Yên Bái', NULL, '0906 834 148', '(539) 917-0954', NULL, '160011322239', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 7', '2021-03-30 00:37:59', 'Hường', '1970-01-01 01:37:34', 'Hoa Nguyễn'),
('72af2231-78a7-7caa-cd1d-086412a8ea97', 'NV-0064', 'Trịnh Huy Thành ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Trưởng phòng', '1994-01-28', 1, '035552219492', '2013-03-11', 'CA Thanh Hóa', 'Số 87 , Âu Cơ, Khánh Hòa', '0123 619 265', '(173) 454-3055', 'Antonina_H.Criswell@misa.com', '203068938773', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 5', '2021-07-16 23:42:18', 'Hường', '1970-01-01 00:00:06', 'Thái Trịnh'),
('73dc79e1-1ccb-35a6-0235-60b3ebf808a9', 'NV-0025', 'Hoàng Văn Thành ', '142cb08f-7c31-21fa-8e90-67245e8b283e', NULL, NULL, NULL, '030071278273', NULL, 'CA Hưng Yên', NULL, NULL, '(600) 822-6166', NULL, '207032142895', NULL, 'Chi nhánh 4', NULL, 'Loan', '2020-01-24 12:19:02', 'Hiếu Trịnh'),
('7485b64f-7835-65a4-8041-c1ec321fe728', 'NV-0091', 'Hoàng Ngọc Hiếu ', '469b3ece-744a-45d5-957d-e8c757976496', 'Giám đốc', '1991-06-15', 0, '030026574909', '2016-07-26', NULL, 'Số 87 , Quang Trung, TP Hồ Chí Minh', '0336 964 684', '(357) 663-5567', 'Hudgens@misa.com', '051065784092', 'Ngân hàng Á Châu', 'Chi nhánh 7', '2021-01-11 19:42:19', 'Loan', '2020-07-31 21:06:39', NULL),
('777132b4-2a33-68d1-26c2-579daad24557', 'NV-0054', 'Nguyễn Đức Tuấn ', '17120d02-6ab5-3e43-18cb-66948daf6128', 'Nhân viên', '2003-12-29', 0, '035567754881', '2018-02-21', 'CA Yên Bái', '', '0906 618 560', '(465) 824-3043', '', '160078416506', 'Ngân hàng Quân đội', 'Chi nhánh 9', '2021-07-12 22:07:30', 'Trường', '1975-02-24 02:44:03', 'Hương Nguyễn'),
('7a763a51-4322-5c5a-b5d2-89b22d10517e', 'NV-0068', 'Tăng Ngọc Linh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Trưởng phòng', '2001-05-26', 2, '', '2010-06-02', 'CA Thanh Hóa', 'Số 27 , Cầu Giấy, Lào Cai', '0336 849 980', '(865) 520-4431', 'Asher@misa.com', '203045695969', 'Ngân hàng Đông Nam Á', 'Chi nhánh 8', '2021-06-05 18:20:28', 'Ly', '1970-01-01 02:05:18', 'Minh Bùi'),
('7ad34860-1ac8-7ad7-d01d-086412a8ea97', 'NV-0029', 'Tăng Huy Thái ', '469b3ece-744a-45d5-957d-e8c757976496', 'Giám đốc', '1999-11-08', 1, '030035160167', '2013-04-07', '', 'Số 25 , Âu Cơ, Hà Giang', '0336 100 857', '(495) 651-7081', 'Crittenden@gmail.com', '051089492586', 'Ngân hàng Tiên Phong', 'Chi nhánh 5', '2021-01-01 00:00:07', 'Cường', '1970-01-01 00:00:04', 'Ly Nguyễn'),
('7b550b8f-7ff9-51bc-0f77-d9ebc53aac3d', 'NV-0062', 'Bùi Thị Diễm ', '142cb08f-7c31-21fa-8e90-67245e8b283e', NULL, NULL, NULL, '035572786876', NULL, 'CA Hà Nam', NULL, NULL, '(875) 588-3115', NULL, '160065134493', NULL, 'Chi nhánh 4', NULL, 'Linh', '1979-12-01 15:08:55', 'Thái Hoàng'),
('7b666cc3-1b67-6037-67f6-423b4e874d0f', 'NV-0038', 'Trần Thị Linh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Trưởng phòng', '1992-05-30', 1, NULL, '2011-03-19', NULL, '', '0961 039 304', '(568) 014-4771', '', '051007611829', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 5', '2021-07-25 19:52:28', 'Loan', '2010-07-10 16:33:56', NULL),
('7bd9cf39-3f55-3a7b-0035-60b3ebf808a9', 'NV-0010', 'Nguyễn Văn Minh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1995-09-02', 2, '030026751218', '2010-08-25', 'CA Hải Dương', 'Số 73 , Nguyễn Trãi, Khánh Hòa', '0123 119 950', '(519) 896-1274', 'Allen.F_Valadez@gmail.com', '207024983258', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 0', '2021-08-12 20:33:46', 'Hương', '1991-11-19 03:01:03', 'Thành Tăng'),
('7c5b9fe7-14c9-3bb5-b4d2-89b22d10517e', 'NV-0063', 'Hoàng Văn Tuấn ', '469b3ece-744a-45d5-957d-e8c757976496', 'Phó phòng', '2001-09-01', 2, NULL, '2012-04-28', 'CA Hòa Bình', 'Số 92 , Nguyễn Trãi, Thanh Hóa', '0123 791 603', NULL, 'WaltonGolden1@misa.com', '160003587696', 'Ngân hàng Kỹ Thương Việt Nam', NULL, '2021-01-01 00:00:07', NULL, NULL, 'Loan Nguyễn'),
('7c80a684-1cb5-41af-ff34-60b3ebf808a9', 'NV-0053', 'Tăng Ngọc Bằng ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Giám đốc', '1992-01-24', 0, '030072193572', '2012-11-07', 'CA Hòa Bình', '', '0906 267 622', '(450) 290-3993', '', '207006976149', 'Ngân hàng Á Châu', 'Chi nhánh 7', '2021-01-01 01:19:23', 'Hoa', '1975-02-13 04:47:19', 'Thái Tăng'),
('7f51ea57-13b2-139f-1177-d9ebc53aac3d', 'NV-0080', 'Nguyễn Thái Hùng ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Nhân viên', '1996-06-29', 1, '030013314688', '2014-02-16', 'CA Hà Giang', NULL, '0961 361 849', '(198) 058-4532', NULL, '051051633266', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 3', '2021-03-27 03:57:07', 'Hường', '2002-12-28 21:18:40', 'Huy Trịnh'),
('83dc79e1-1ccb-35a6-0235-60b3ebf808a9', 'NV-0075', 'Hoàng Văn Thành ', '142cb08f-7c31-21fa-8e90-67245e8b283e', NULL, NULL, NULL, '030071278273', NULL, 'CA Hưng Yên', NULL, NULL, '(600) 822-6166', NULL, '207032142895', NULL, 'Chi nhánh 4', NULL, 'Loan', '2020-01-24 12:19:02', 'Hiếu Trịnh'),
('8ad34860-1ac8-7ad7-d01d-086412a8ea97', 'NV-0079', 'Tăng Huy Thái ', '469b3ece-744a-45d5-957d-e8c757976496', 'Giám đốc', '1999-11-08', 1, '030035160167', '2013-04-07', '', 'Số 25 , Âu Cơ, Hà Giang', '0336 100 857', '(495) 651-7081', 'Crittenden@gmail.com', '051089492586', 'Ngân hàng Tiên Phong', 'Chi nhánh 5', '2021-01-01 00:00:07', 'Cường', '1970-01-01 00:00:04', 'Ly Nguyễn'),
('8b666cc3-1b67-6037-67f6-423b4e874d0f', 'NV-0088', 'Trần Thị Linh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Trưởng phòng', '1992-05-30', 1, NULL, '2011-03-19', NULL, '', '0961 039 304', '(568) 014-4771', '', '051007611829', 'Ngân hàng Đầu tư và Phát triển Việt Nam', 'Chi nhánh 5', '2021-07-25 19:52:28', 'Loan', '2010-07-10 16:33:56', NULL),
('8bd9cf39-3f55-3a7b-0035-60b3ebf808a9', 'NV-0060', 'Nguyễn Văn Minh ', '4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Nhân viên', '1995-09-02', 2, '030026751218', '2010-08-25', 'CA Hải Dương', 'Số 73 , Nguyễn Trãi, Khánh Hòa', '0123 119 950', '(519) 896-1274', 'Allen.F_Valadez@gmail.com', '207024983258', 'Ngân hàng Kỹ Thương Việt Nam', 'Chi nhánh 0', '2021-08-12 20:33:46', 'Hương', '1991-11-19 03:01:03', 'Thành Tăng');